---
name: 'Base Tools'
description: 'Install base tools on GHA runners'
inputs:
  install-java:
    description: 'Install GraalVM JDK 25'
    required: false
    default: 'true'
  cache-maven:
    description: 'Enable Maven dependency caching'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up GraalVM JDK 25
      if: inputs.install-java == 'true'
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'graalvm'
        cache: ${{ inputs.cache-maven == 'true' && 'maven' || '' }}
        # ALWAYS define the server
        server-id: github
        server-username: ${{ env.MAVEN_USERNAME }}
        server-password: ${{ env.MAVEN_PASSWORD }}

    - name: Install Taskfile
      shell: bash
      run: |
        curl -sL https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin

    - name: Install Commitizen
      shell: bash
      run: pip install --quiet commitizen
